version: '2'
services:
  postgres_photo_storage:
    image: postgres:10
    environment:
     POSTGRES_PASSWORD: "admin"
     PGDATA: "/PG_DATA"
    container_name: postgres_photo_storage
    restart: unless-stopped
    volumes:
       - "/PG_DATA_PHOTO_STORAGE:/PG_DATA"
    ports:
        - "5454:5432"
